const USERS = {
  'owner@petcare.id': { name: 'Dr. Siti Rahma', role: 'owner', roleLabel: 'Owner', email: 'owner@petcare.id' },
  'dokter@petcare.id': { name: 'Dr. Ahmad Fauzi', role: 'doctor', roleLabel: 'Doctor', email: 'dokter@petcare.id' },
  'staff@petcare.id': { name: 'Dewi Kusuma', role: 'staff', roleLabel: 'Staff Klinis', email: 'staff@petcare.id' },
  'budi@gmail.com': { name: 'Budi Santoso', role: 'customer', roleLabel: 'Pemilik Hewan', email: 'budi@gmail.com' },
};

const DATA = {
  appointments: [
    { id: 1, date: '2024-06-15', time: '09:00', customer: 'Budi Santoso', pet: 'Max (Labrador)', doctor: 'Dr. Ahmad Fauzi', type: 'Pemeriksaan Umum', status: 'confirmed' },
    { id: 2, date: '2024-06-15', time: '10:30', customer: 'Sari Dewi', pet: 'Luna (Poodle)', doctor: 'Dr. Ahmad Fauzi', type: 'Vaksinasi', status: 'waiting' },
    { id: 3, date: '2024-06-15', time: '13:00', customer: 'Andi Wahyu', pet: 'Buddy (Golden Retriever)', doctor: 'Dr. Ahmad Fauzi', type: 'Kontrol Pasca Operasi', status: 'completed' },
    { id: 4, date: '2024-06-16', time: '09:30', customer: 'Rina Lestari', pet: 'Mochi (Kucing)', doctor: 'Dr. Ahmad Fauzi', type: 'Grooming', status: 'confirmed' },
    { id: 5, date: '2024-06-16', time: '11:00', customer: 'Budi Santoso', pet: 'Bella (Shih Tzu)', doctor: 'Dr. Ahmad Fauzi', type: 'Pemeriksaan Kulit', status: 'confirmed' },
  ],
  customers: [
    { id: 1, name: 'Budi Santoso', phone: '081234567890', email: 'budi@gmail.com', pets: 2, lastVisit: '2024-06-10', status: 'active' },
    { id: 2, name: 'Sari Dewi', phone: '085678901234', email: 'sari@gmail.com', pets: 1, lastVisit: '2024-06-12', status: 'active' },
    { id: 3, name: 'Andi Wahyu', phone: '087890123456', email: 'andi@gmail.com', pets: 3, lastVisit: '2024-06-08', status: 'active' },
    { id: 4, name: 'Rina Lestari', phone: '089012345678', email: 'rina@gmail.com', pets: 1, lastVisit: '2024-05-30', status: 'active' },
    { id: 5, name: 'Dian Pratama', phone: '082345678901', email: 'dian@gmail.com', pets: 2, lastVisit: '2024-06-01', status: 'inactive' },
  ],
  pets: [
    { id: 1, name: 'Max', species: 'Anjing', breed: 'Labrador', age: '3 thn', gender: 'Jantan', owner: 'Budi Santoso', weight: '28 kg', status: 'Sehat' },
    { id: 2, name: 'Bella', species: 'Anjing', breed: 'Shih Tzu', age: '2 thn', gender: 'Betina', owner: 'Budi Santoso', weight: '5.2 kg', status: 'Sehat' },
    { id: 3, name: 'Luna', species: 'Anjing', breed: 'Poodle', age: '4 thn', gender: 'Betina', owner: 'Sari Dewi', weight: '7 kg', status: 'Kontrol' },
    { id: 4, name: 'Buddy', species: 'Anjing', breed: 'Golden Retriever', age: '5 thn', gender: 'Jantan', owner: 'Andi Wahyu', weight: '32 kg', status: 'Rawat Inap' },
    { id: 5, name: 'Mochi', species: 'Kucing', breed: 'Persian', age: '1 thn', gender: 'Betina', owner: 'Rina Lestari', weight: '3.5 kg', status: 'Sehat' },
  ],
  medicalRecords: [
    { id: 1, date: '2024-06-10', pet: 'Max (Labrador)', owner: 'Budi Santoso', doctor: 'Dr. Ahmad Fauzi', complaint: 'Nafsu makan berkurang', diagnosis: 'Gastritis ringan', treatment: 'Antasida + diet rendah lemak', status: 'completed' },
    { id: 2, date: '2024-06-12', pet: 'Luna (Poodle)', owner: 'Sari Dewi', doctor: 'Dr. Ahmad Fauzi', complaint: 'Vaksinasi rutin', diagnosis: 'Sehat', treatment: 'Vaksin Rabies + Distemper', status: 'completed' },
    { id: 3, date: '2024-06-08', pet: 'Buddy (Golden Retriever)', owner: 'Andi Wahyu', doctor: 'Dr. Ahmad Fauzi', complaint: 'Kaki depan pincang', diagnosis: 'Ligamen robek ringan', treatment: 'Anti-inflamasi + istirahat 2 minggu', status: 'follow-up' },
  ],
  vaccinations: [
    { id: 1, pet: 'Max', owner: 'Budi Santoso', vaccine: 'Rabies', date: '2024-01-15', nextDue: '2025-01-15', doctor: 'Dr. Ahmad Fauzi', status: 'valid' },
    { id: 2, pet: 'Luna', owner: 'Sari Dewi', vaccine: 'DHPPiL', date: '2024-03-20', nextDue: '2025-03-20', doctor: 'Dr. Ahmad Fauzi', status: 'valid' },
    { id: 3, pet: 'Mochi', owner: 'Rina Lestari', vaccine: 'FVRCP', date: '2023-12-10', nextDue: '2024-06-16', doctor: 'Dr. Ahmad Fauzi', status: 'due' },
    { id: 4, pet: 'Buddy', owner: 'Andi Wahyu', vaccine: 'Bordetella', date: '2023-11-05', nextDue: '2024-05-05', doctor: 'Dr. Ahmad Fauzi', status: 'overdue' },
  ],
  inpatients: [
    { id: 1, pet: 'Buddy (Golden Retriever)', owner: 'Andi Wahyu', room: 'A-1', admitted: '2024-06-08', doctor: 'Dr. Ahmad Fauzi', reason: 'Ligamen robek', status: 'active', days: 7 },
    { id: 2, pet: 'Whisky (Kucing)', owner: 'Dian Pratama', room: 'B-2', admitted: '2024-06-13', doctor: 'Dr. Ahmad Fauzi', reason: 'Infeksi saluran napas', status: 'active', days: 2 },
  ],
  grooming: [
    { id: 1, date: '2024-06-15', pet: 'Luna (Poodle)', owner: 'Sari Dewi', services: 'Mandi + Potong', staff: 'Dewi', price: 150000, status: 'in-progress' },
    { id: 2, date: '2024-06-15', pet: 'Mochi (Kucing)', owner: 'Rina Lestari', services: 'Full Grooming', staff: 'Dewi', price: 200000, status: 'completed' },
    { id: 3, date: '2024-06-14', pet: 'Max (Labrador)', owner: 'Budi Santoso', services: 'Mandi + Sisir', staff: 'Dewi', price: 100000, status: 'completed' },
  ],
  inventory: [
    { id: 1, name: 'Amoxicillin 250mg', category: 'Antibiotik', stock: 120, unit: 'kapsul', minStock: 50, expiry: '2025-08-01', price: 'Rp 3.500' },
    { id: 2, name: 'Metronidazole Tablet', category: 'Antibiotik', stock: 80, unit: 'tablet', minStock: 30, expiry: '2025-06-15', price: 'Rp 2.800' },
    { id: 3, name: 'Infus NaCl 500ml', category: 'Cairan Infus', stock: 15, unit: 'botol', minStock: 20, expiry: '2025-12-01', price: 'Rp 25.000' },
    { id: 4, name: 'Jarum Suntik 5cc', category: 'Alat Medis', stock: 200, unit: 'pcs', minStock: 50, expiry: '2026-01-01', price: 'Rp 1.500' },
    { id: 5, name: 'Vitamin B Complex', category: 'Suplemen', stock: 5, unit: 'botol', minStock: 10, expiry: '2024-09-01', price: 'Rp 45.000' },
  ],
  products: [
    { id: 1, name: 'Royal Canin Medium Adult', category: 'Makanan', price: 350000, stock: 25 },
    { id: 2, name: 'Whiskas Tuna 400g', category: 'Makanan', price: 28000, stock: 50 },
    { id: 3, name: 'Shampoo Anti-Kutu', category: 'Perawatan', price: 65000, stock: 30 },
    { id: 4, name: 'Tali Leash Nylon', category: 'Aksesori', price: 45000, stock: 20 },
    { id: 5, name: 'Mainan Bola Karet', category: 'Aksesori', price: 25000, stock: 40 },
    { id: 6, name: 'Tempat Makan Stainless', category: 'Aksesori', price: 55000, stock: 15 },
    { id: 7, name: 'Obat Cacing Universal', category: 'Obat', price: 85000, stock: 35 },
    { id: 8, name: 'Vitamin C Anjing', category: 'Suplemen', price: 120000, stock: 12 },
  ],
  invoices: [
    { id: 'INV-001', date: '2024-06-10', customer: 'Budi Santoso', services: 'Pemeriksaan + Obat', amount: 'Rp 350.000', status: 'paid' },
    { id: 'INV-002', date: '2024-06-12', customer: 'Sari Dewi', services: 'Vaksinasi Rabies', amount: 'Rp 250.000', status: 'paid' },
    { id: 'INV-003', date: '2024-06-14', customer: 'Rina Lestari', services: 'Grooming Full', amount: 'Rp 200.000', status: 'unpaid' },
    { id: 'INV-004', date: '2024-06-15', customer: 'Andi Wahyu', services: 'Rawat Inap 7 hari', amount: 'Rp 1.750.000', status: 'unpaid' },
    { id: 'INV-005', date: '2024-06-16', customer: 'Sari Dewi', services: 'Obat & Konsultasi', amount: 'Rp 420.000', status: 'paid' },
  ],
  revenueTrend: [
    { day: 'Mon', value: 820000 },
    { day: 'Tue', value: 940000 },
    { day: 'Wed', value: 710000 },
    { day: 'Thu', value: 1080000 },
    { day: 'Fri', value: 960000 },
    { day: 'Sat', value: 1240000 },
    { day: 'Sun', value: 1120000 },
  ],
  appointmentTrend: [
    { day: 'Mon', count: 8 },
    { day: 'Tue', count: 10 },
    { day: 'Wed', count: 7 },
    { day: 'Thu', count: 12 },
    { day: 'Fri', count: 9 },
    { day: 'Sat', count: 14 },
    { day: 'Sun', count: 11 },
  ],
  topServices: [
    { name: 'Pemeriksaan Umum', value: 42 },
    { name: 'Vaksinasi', value: 28 },
    { name: 'Grooming', value: 18 },
    { name: 'Rawat Inap', value: 11 },
  ],
  topProducts: [
    { name: 'Royal Canin Medium Adult', sold: 38 },
    { name: 'Whiskas Tuna 400g', sold: 29 },
    { name: 'Obat Cacing Universal', sold: 21 },
    { name: 'Shampoo Anti-Kutu', sold: 17 },
  ],
  doctorPerformance: [
    { name: 'Dr. Ahmad Fauzi', completed: 28, rating: 4.9 },
    { name: 'Dr. Siti Rahma', completed: 23, rating: 4.8 },
    { name: 'Dr. Kartika Novi', completed: 18, rating: 4.7 },
  ],
  branches: [
    { name: 'Jakarta', revenueToday: 450000, revenueMonth: 8200000, activePatients: 26, activeCustomers: 48, groomingRevenue: 860000, pharmacyRevenue: 1260000, outstandingInvoices: 6, inventoryHealth: 'Stabil' },
    { name: 'Bandung', revenueToday: 320000, revenueMonth: 6200000, activePatients: 19, activeCustomers: 35, groomingRevenue: 520000, pharmacyRevenue: 980000, outstandingInvoices: 4, inventoryHealth: 'Waspada' },
    { name: 'Surabaya', revenueToday: 380000, revenueMonth: 7100000, activePatients: 22, activeCustomers: 41, groomingRevenue: 610000, pharmacyRevenue: 1040000, outstandingInvoices: 5, inventoryHealth: 'Stabil' },
  ],
  expenses: [
    { category: 'Operasional Klinik', amount: 2100000 },
    { category: 'Gaji Staff', amount: 1350000 },
    { category: 'Pembelian Alat', amount: 780000 },
  ],
  purchaseOrders: [
    { id: 'PO-101', vendor: 'PT Medika Farma', date: '2024-06-12', status: 'approval', total: 'Rp 2.850.000' },
    { id: 'PO-102', vendor: 'PT Pet Supplies', date: '2024-06-14', status: 'received', total: 'Rp 1.250.000' },
    { id: 'PO-103', vendor: 'PT Klinik Center', date: '2024-06-15', status: 'pending', total: 'Rp 980.000' },
  ],
  stockMovement: [
    { id: 'SM-001', type: 'incoming', item: 'Metronidazole Tablet', qty: 50, date: '2024-06-12', note: 'Terima barang PO-101' },
    { id: 'SM-002', type: 'outgoing', item: 'Amoxicillin 250mg', qty: 20, date: '2024-06-13', note: 'Resep pasien' },
    { id: 'SM-003', type: 'adjustment', item: 'Vitamin B Complex', qty: -5, date: '2024-06-14', note: 'Koreksi stok' },
  ],
  transactions: [
    { id: 'TR-001', date: '2024-06-15', type: 'Revenue', description: 'Pemeriksaan Umum + Obat', amount: 'Rp 350.000' },
    { id: 'TR-002', date: '2024-06-15', type: 'Expense', description: 'Pembelian obat', amount: 'Rp 180.000' },
    { id: 'TR-003', date: '2024-06-15', type: 'Revenue', description: 'Grooming Full', amount: 'Rp 200.000' },
    { id: 'TR-004', date: '2024-06-16', type: 'Revenue', description: 'Vaksinasi Rabies', amount: 'Rp 250.000' },
  ],
  reportTemplates: [
    { key: 'appointment', title: 'Appointment Report', description: 'Ringkasan jadwal dan kepuasan pasien.' },
    { key: 'medical', title: 'Medical Report', description: 'Laporan rekam medis dan kasus klinik.' },
    { key: 'vaccination', title: 'Vaccination Report', description: 'Status vaksinasi dan jadwal pengingat.' },
    { key: 'inventory', title: 'Inventory Report', description: 'Stok, kedaluwarsa, dan PO.' },
    { key: 'grooming', title: 'Grooming Report', description: 'Pendapatan grooming dan layanan.' },
    { key: 'revenue', title: 'Revenue Report', description: 'Analisa pendapatan harian dan bulanan.' },
    { key: 'customer', title: 'Customer Report', description: 'Profil pelanggan dan kunjungan.' },
  ],
  notifications: [
    { id: 1, type: 'appointment', title: 'Appointment 10:30 untuk Luna menunggu konfirmasi', time: '5 menit lalu', status: 'unread' },
    { id: 2, type: 'vaccine', title: 'Vaksinasi Mochi jatuh tempo besok', time: '1 jam lalu', status: 'unread' },
    { id: 3, type: 'invoice', title: 'Invoice INV-004 belum dibayar', time: '3 jam lalu', status: 'read' },
    { id: 4, type: 'stock', title: 'Vitamin B Complex stok menipis', time: '6 jam lalu', status: 'unread' },
  ],
  bookingSlots: [
    { id: 1, service: 'Pemeriksaan Umum', doctor: 'Dr. Ahmad Fauzi', date: '2024-06-18', time: '09:30', available: true },
    { id: 2, service: 'Vaksinasi', doctor: 'Dr. Ahmad Fauzi', date: '2024-06-18', time: '11:00', available: true },
    { id: 3, service: 'Grooming', doctor: 'Dr. Ahmad Fauzi', date: '2024-06-19', time: '13:00', available: true },
    { id: 4, service: 'Konsultasi Kulit', doctor: 'Dr. Ahmad Fauzi', date: '2024-06-20', time: '15:00', available: false },
  ],
  bookings: [
    { id: 1, customer: 'Budi Santoso', pet: 'Max (Labrador)', service: 'Pemeriksaan Umum', doctor: 'Dr. Ahmad Fauzi', date: '2024-06-18', time: '09:30', status: 'confirmed' },
  ],
  customerVisits: [
    { id: 1, pet: 'Max', species: 'Anjing', breed: 'Labrador', age: '3 thn', weight: '28 kg', photo: 'pet-photo-1', status: 'Sehat' },
    { id: 2, pet: 'Bella', species: 'Anjing', breed: 'Shih Tzu', age: '2 thn', weight: '5.2 kg', photo: 'pet-photo-2', status: 'Sehat' },
  ],
  customerInvoices: [
    { id: 'INV-005', date: '2024-06-16', amount: 'Rp 420.000', status: 'paid', description: 'Konsultasi & Obat' },
    { id: 'INV-006', date: '2024-06-15', amount: 'Rp 200.000', status: 'unpaid', description: 'Grooming Full' },
  ],
};

const MENUS = {
  owner: [
    { section: 'UTAMA' },
    { id: 'dashboard', icon: 'bar-chart-2', label: 'Dashboard' },
    { section: 'KLINIS' },
    { id: 'appointments', icon: 'calendar', label: 'Appointment' },
    { id: 'medical-records', icon: 'file-text', label: 'Rekam Medis' },
    { id: 'vaccination', icon: 'shield-check', label: 'Vaksinasi' },
    { id: 'monitoring', icon: 'heart-pulse', label: 'Monitoring' },
    { id: 'inpatient', icon: 'bed', label: 'Rawat Inap' },
    { section: 'OPERASIONAL' },
    { id: 'customers', icon: 'users', label: 'Pelanggan' },
    { id: 'pets', icon: 'paw-print', label: 'Data Hewan' },
    { id: 'grooming', icon: 'scissors', label: 'Grooming' },
    { id: 'inventory', icon: 'box', label: 'Inventori' },
    { section: 'KOMERSIAL' },
    { id: 'products', icon: 'shopping-bag', label: 'Produk Petshop' },
    { id: 'pos', icon: 'credit-card', label: 'Kasir (POS)' },
    { id: 'invoices', icon: 'file', label: 'Invoice' },
    { id: 'accounting', icon: 'trending-up', label: 'Akuntansi' },
    { section: 'MANAJEMEN' },
    { id: 'reports', icon: 'pie-chart', label: 'Laporan' },
    { id: 'users', icon: 'user-check', label: 'Pengguna' },
    { id: 'settings', icon: 'settings', label: 'Pengaturan' },
  ],
  doctor: [
    { section: 'UTAMA' },
    { id: 'dashboard', icon: 'bar-chart-2', label: 'Dashboard' },
    { section: 'KLINIS' },
    { id: 'appointments', icon: 'calendar', label: 'Appointment' },
    { id: 'medical-records', icon: 'file-text', label: 'Rekam Medis' },
    { id: 'vaccination', icon: 'shield-check', label: 'Vaksinasi' },
    { id: 'monitoring', icon: 'heart-pulse', label: 'Monitoring' },
  ],
  staff: [
    { section: 'UTAMA' },
    { id: 'dashboard', icon: 'bar-chart-2', label: 'Dashboard' },
    { section: 'OPERASIONAL' },
    { id: 'appointments', icon: 'calendar', label: 'Appointment' },
    { id: 'customers', icon: 'users', label: 'Pelanggan' },
    { id: 'pets', icon: 'paw-print', label: 'Data Hewan' },
    { id: 'grooming', icon: 'scissors', label: 'Grooming' },
    { id: 'inventory', icon: 'box', label: 'Inventori' },
    { id: 'inpatient', icon: 'bed', label: 'Rawat Inap' },
    { section: 'KASIR' },
    { id: 'products', icon: 'shopping-bag', label: 'Produk' },
    { id: 'pos', icon: 'credit-card', label: 'Kasir (POS)' },
    { id: 'invoices', icon: 'file', label: 'Invoice' },
  ],
  customer: [
    { section: 'PORTAL PELANGGAN' },
    { id: 'dashboard', icon: 'home', label: 'Beranda' },
    { id: 'my-pets', icon: 'paw-print', label: 'Hewan Saya' },
    { id: 'my-appointments', icon: 'calendar', label: 'Jadwal Kunjungan' },
    { id: 'my-medical', icon: 'file-text', label: 'Rekam Medis' },
    { id: 'my-vaccination', icon: 'shield-check', label: 'Vaksinasi' },
    { id: 'my-invoices', icon: 'file', label: 'Invoice Saya' },
    { id: 'my-profile', icon: 'user', label: 'Profil Saya' },
  ],
};
